name: Books
main: me.jonna.CustomBook.Main
version: 2.2.0
authors: [jn1234]
website: http://dev.bukkit.org/bukkit-plugins/custom-book/
description: Custom book plugin by jn1234
commands:
    cb:
        description: CustomBook commands
    custombook:
        description: CustomBook commands