name: Books
main: me.jonna.CustomBook.Main
version: 2.0.0
description: Custom book plugin by jn1234
commands:
    cb:
        description: CustomBook commands
    custombook:
        description: CustomBook commands
permissions:
  books.admin:
    description: All books commands
    children:
      books.custom.*: true
      books.join.*: true
      books.create.*: true
      books.reload: true
      books.help: true
  books.user:
    description: Commands meant for users
    children:
      books.custom.*: true
      books.join.*: true
      books.help: true